### ISSUE TITLE
Change YAML format for better consistency

### ISSUE THREAD

**Issue by BurningEnlightenment** [deeplex/copier-copier#10]
**Problem Description**

Currently the indendation mismatches for YAML objects and lists:
```yml
hello:
    # 4 spaces
    prop-list:
        - obj-item-prop: 1j
          # seemingly 2 spaces
          oprop: 42
```

**Proposed Solution**

Specify 2 space indendation for YAML (`*.yml` and `*.yaml`) files via editorconfig.

**Additional Context**

VS Code has no notion of contextually dependent indendation:
![grafik](https://user-images.githubusercontent.com/5796962/179246432-b5c7f714-3b7f-4f28-99a6-5307b25c49cd.png)
